#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to respect above requirements
# Install Nginx
sudo apt-get update
sudo apt-get -y install nginx

# Configure Nginx to serve "Hello World!"
sudo sed -i 's|server_name _;|server_name _;\n\n\tlocation / {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}|g' /etc/nginx/sites-available/default

# Restart Nginx
sudo /etc/init.d/nginx restart
