#!/usr/bin/env bash
# Install Nginx
sudo apt-get update
sudo apt-get install nginx -y

# Edit Nginx configuration file to add custom header
sudo sed -i '/http {/a\        add_header X-Served-By $hostname;' /etc/nginx/nginx.conf

# Restart Nginx
sudo systemctl restart nginx

